# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :test_old do
    run_tests(project: "Test_Center_Bug.xcodeproj", devices: ["iPhone 8"], scheme: "Test_Center_Bug")
  end


  lane :sweep do
    test_run_block = lambda do |testrun_info|
      failed_test_count = testrun_info[:failed].size
    
      if failed_test_count > 0
        UI.important('The run of tests would finish with failures due to fragile tests here.')

        try_attempt = testrun_info[:try_count]
        if try_attempt < 3
          UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
        end
      end
    end
  
    result = multi_scan(
      project: "Test_Center_Bug.xcodeproj",
      try_count: 3,
      fail_build: false,
      scheme: 'Test_Center_Bug',
      testrun_completed_block: test_run_block,
      parallel_testrun_count: 4, 
      devices: ["iPhone 8 (13.1)"],
    )
    unless result[:failed_testcount].zero?
      UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
    end
  end

end
